server:
  port: 0

spring:
  application:
    name: api
  jpa:
    database: POSTGRESQL
    show-sql: true
    properties:
      hibernate:
        ddl-auto: update
        autoregister_listeners: true
        serach:
          default:
            directory_provider: filesystem
            indexBase: lat

  datasource:
    jdbcUrl: jdbc:postgresql://localhost:5433/client_db
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  second-datasource:
    jdbcUrl: jdbc:postgresql://localhost:5433/gpus_db
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka